<!DOCTYPE html>
<html lang="en">

	<?php $this->getHead(); ?>
	
	<body>
		<?php $this->getHelper("header"); ?>
		
		<!-- Jumbotron -->
		<section class="full video" id="home">
			Hometown: Norfolk, VA

			I grew up listening to: Tupac, Dipset, Mase. Tupac represented the struggle, his music was lessons but at the same time you could groove to it. I always had a passion for learning so his music attracted me from the start. Mase’s music told stories of every day life of a youngin’. I was 13 when Harlem World dropped and just started dating girls and that album was the manual of how to handle them. Dipset was just the freshest crew out in 2003-2005 era and my crew wanted to be just like them. I remember I bought Pelle Pelle leathers & peanut butter Timberlands right after them, they music painted pictures of how to ball.
			
			Most people don’t know I: Most people don’t know that I have been shot six times, made it to tell the story and that’s why appreciating life every day is so important to me. Also what people don’t know is I had a major name as a promoter in Virginia before rap. Me and my company brought every major act you can name to the area. Also I starred in many of Clipse’s video such as “Exodus,” “Cook It Down,” “Door Man” and more, I have just as much love for theatre as I do music.
			
			My style’s been compared to: I’ve been compared to Tupac for the fact that we both thuggish but very intelligent as the same time, our flow is very conversational and paint clear pictures of reality, most of all we both have a second passion for theatre! All around entertainers.
			
			My standout records and/or moments to date have been: “Gutta Gutta” stands out because it gave the whole world an in depth description of my city. It’s the No. 1 record in Virginia because it represent our every day struggle and defeat in a proud manner. “Making Of A Man” stands out because its basically a dairy of my life from the beginning to now, so many people been through the same thing, they walk up to me saying I’m rapping their life too.
			
			My goal in Hip-Hop is: My goal in hip-hop is to become another example to younger people that anything possible. I want listeners to look at me as a teacher of education even though some of my lyrics may be a bit of explicit but it all has a positive message at the end! I want to show people how hip-hop can be an avenue to help make the urban community a better place rather then sending negative messages to our youth as its been stereotypically acclaimed!
			
			I’m gonna be the next: I’m going to b the next to tell my real life story in which so many people are afraid to do and make a living off it to make a better life for my family and my hood.
		</section>
		
		<?php $this->getHelper("footer");?>
		
		<!--LOAD SCRIPTS-->
		<script src="js/jquery-1.11.0.js"></script>
		<script type="text/javascript" src="js/jquery.modal.js"></script>
		<script type="text/javascript" src="js/bootstrap.min.js"></script>
		<script type="text/javascript" src="js/plugins.js"></script>
		<script type="text/javascript" src="js/custom.js"></script>
		<script type="text/javascript" src="js/style.js"></script>
		<script type="text/javascript" src="js/video.js"></script>
		<script type="text/javascript" src="js/show-modals.js"></script>
	   
	    <?php $this->getHelper("image_modal"); ?>
	    <?php $this->getHelper("contact_modal"); ?>
	</body>
</html>