<!DOCTYPE html>
<html lang="en">

	<?php $this->getHead(); ?>
	
	<body>
		<?php $this->getHelper("header"); ?>
		
		<!-- Jumbotron -->
		<section class="full video" id="home">
			<iframe id="ytplayer" type="text/html" width="100%" height="550"
					src="http://www.youtube.com/embed/5JfBxYl5ue4?autoplay=1&controls=0&showinfo=0&theme=light"
					frameborder="0" allowfullscreen>
			</iframe>
		</section>
		
		<?php $this->getHelper("footer");?>
		
		<!--LOAD SCRIPTS-->
		<script src="js/jquery-1.11.0.js"></script>
		<script type="text/javascript" src="js/jquery.modal.js"></script>
		<script type="text/javascript" src="js/bootstrap.min.js"></script>
		<script type="text/javascript" src="js/plugins.js"></script>
		<script type="text/javascript" src="js/custom.js"></script>
		<script type="text/javascript" src="js/style.js"></script>
		<script type="text/javascript" src="js/video.js"></script>
		<script type="text/javascript" src="js/show-modals.js"></script>
	   
	    <?php $this->getHelper("image_modal"); ?>
	    <?php $this->getHelper("contact_modal"); ?>
	</body>
</html>