<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Young Money Yawn</title>
    <meta name="author" content="">
    <meta name="description" content="">
    <link href='http://fonts.googleapis.com/css?family=Raleway:300,400,500' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="css/framework.css">
    <link rel="stylesheet" type="text/css" href="css/plugins.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="css/contact.css">
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>

<body>
	<header>
		<div class="wrapper clearfix">
			<div class="one_fourth remove_bottom logo">
				<a href="index.html">
					<img src="img/logo.png" alt="logo" id ="logoHead"class="retina" />
				</a>
			</div><!--/one_fourth-->
			<div class="three_fourths remove_bottom last">
				<nav>
					<ul id="selectnav">
						<li>
							<a href="#home" class="scroller active">Home</a>
						</li>
						<li>
							<a href="#video" class="scroller">Videos</a>
						</li>
						<li>
							<a href="#pics" class="scroller">Pics</a>
						</li>
						<li>
							<a href="#mixtapes" class="scroller">Mixtapes</a>
						</li>
						<li>
							<a href="#contact" class="scroller">Contact</a>
						</li>
					</ul>
				</nav>
			</div><!--/three_fourths-->
		</div><!--/wrapper-->
	</header><!--/header-->
	
	<section class="full video" id="home">
		<h1 class="mega"><img src="img/wlogo.png" alt="logo" style="opacity:0.15"></h1>
		<a class="button white light scroller" href="#video">More Videos</a>
		<a class="mute muted" href="#"><i class="fa fa-volume-up"></i></a>
	</section>

	<!-- Video Section -->
	<section class="small-padding" id="video">
		<div class="wrapper">
			<h3 class="floatleft">Videos<small class="video-filter"></small></h3>
			<div class="clear"></div><!--CLEAR FLOATS-->
		</div>
	</section>
	
	<section class="dark-wrapper">
		<div class="wrapper overflow-hidden">
		<div id="loader"></div>
			<ul class="clearfix video-isotope video scroll-animate bottom">
			    <?php foreach($this->videos->data as $video){?>		
				<li  class="web-design illustration">
					<a href="#" id="vidModal" class="isotope-alt-image" data-toggle="modal" data-target="#videoModal">
						<img src=<?php echo $video->thumbnail?> alt="image" />
						<div>
							<h5><?php echo $video->description?></h5>
						</div>
					</a>
					<div class="isotope-alt-details">
						<div>
							<h4 class="remove-bottom"><?php echo $video->caption?></h4>
						</div>
					</div>
				</li>
				<?php }?>
			</ul>
			<a href="#" id="load-more" class="scroll-animate top">More Videos</a>
		</div>
	</section>
	
    <!-- Picture Section -->
	<section class="small-padding" id="pics">
		<div class="wrapper">
			<h3 class="floatleft">Pics<small></small></h3>
			<div class="clear"></div><!--CLEAR FLOATS-->
		</div>
	</section>
	
	<section class="dark-wrapper">
		<div class="wrapper">
            <div class="container">
    <div class="row">
		<div class="col-md-12">
                <div id="Carousel" class="carousel slide">
                 
                <ol class="carousel-indicators">
                    <li data-target="#Carousel" data-slide-to="0" class="active"></li>
                    <li data-target="#Carousel" data-slide-to="1"></li>
                    <li data-target="#Carousel" data-slide-to="2"></li>
                </ol>
                 
                <!-- Carousel items -->
                <div class="carousel-inner">
                    
                <div class="item active">
                	<div class="row">
                	  <div class="col-md-3"><a href="#" class="thumbnail"><img src="http://placehold.it/250x250" alt="Image" style="max-width:100%;"></a></div>
                	  <div class="col-md-3"><a href="#" class="thumbnail"><img src="http://placehold.it/250x250" alt="Image" style="max-width:100%;"></a></div>
                	  <div class="col-md-3"><a href="#" class="thumbnail"><img src="http://placehold.it/250x250" alt="Image" style="max-width:100%;"></a></div>
                	  <div class="col-md-3"><a href="#" class="thumbnail"><img src="http://placehold.it/250x250" alt="Image" style="max-width:100%;"></a></div>
                	</div><!--.row-->
                </div><!--.item-->
                 
                <div class="item">
                	<div class="row">
                		<div class="col-md-3"><a href="#" class="thumbnail"><img src="http://placehold.it/250x250" alt="Image" style="max-width:100%;"></a></div>
                		<div class="col-md-3"><a href="#" class="thumbnail"><img src="http://placehold.it/250x250" alt="Image" style="max-width:100%;"></a></div>
                		<div class="col-md-3"><a href="#" class="thumbnail"><img src="http://placehold.it/250x250" alt="Image" style="max-width:100%;"></a></div>
                		<div class="col-md-3"><a href="#" class="thumbnail"><img src="http://placehold.it/250x250" alt="Image" style="max-width:100%;"></a></div>
                	</div><!--.row-->
                </div><!--.item-->
                 
                <div class="item">
                	<div class="row">
                		<div class="col-md-3"><a href="#" class="thumbnail"><img src="http://placehold.it/250x250" alt="Image" style="max-width:100%;"></a></div>
                		<div class="col-md-3"><a href="#" class="thumbnail"><img src="http://placehold.it/250x250" alt="Image" style="max-width:100%;"></a></div>
                		<div class="col-md-3"><a href="#" class="thumbnail"><img src="http://placehold.it/250x250" alt="Image" style="max-width:100%;"></a></div>
                		<div class="col-md-3"><a href="#" class="thumbnail"><img src="http://placehold.it/250x250" alt="Image" style="max-width:100%;"></a></div>
                	</div><!--.row-->
                </div><!--.item-->
                 
                </div><!--.carousel-inner-->
                  <a data-slide="prev" href="#Carousel" class="left carousel-control">‹</a>
                  <a data-slide="next" href="#Carousel" class="right carousel-control">›</a>
                </div><!--.Carousel-->
 
		        </div>
	        </div>
         </div><!--.container-->
	        <div class="clear"></div>
       </div>
    </div>
	</section>
	
    <!-- Mixtapes Section -->
	<section id="mixtapes" class="small-padding" >
		<div  class="wrapper">
			<h3 class="floatleft">Mixtapes<small></small></h3>
			<div class="clear"></div><!--CLEAR FLOATS-->
		</div>
	</section>
	
	<section class="dark-wrapper">
		<div class="wrapper">
			<ul class="clearfix video-isotope">		
				<li class="scroll-animate left member">
					<a href="#" class="isotope-alt-image">
						<img src="img/team1.jpg" alt="image" />
						<div>
							<h4>Mixtape title<small>"Mixtape info"</small></h4>
						</div>
					</a>
					<div class="isotope-alt-details">
						<div>
							<h4 class="remove-bottom">Mixtape title</h4>
							<p class="meta">Mixtape releasedate</p>
						</div>
					</div>
				</li>
				<li class="scroll-animate bottom">
					<a href="#" class="isotope-alt-image">
						<img src="img/team2.jpg" alt="image" />
						<div>
							<h4>Mixtape title<small>"Mixtape info"</small></h4>
						</div>
					</a>
					<div class="isotope-alt-details">
						<div>
							<h4 class="remove-bottom">Mixtape title</h4>
							<p class="meta">Mixtape releasedate</p>
						</div>
					</div>
				</li>
				<li class="scroll-animate right">
					<a href="#" class="isotope-alt-image">
						<img src="img/team3.jpg" alt="image" />
						<div>
							<h4>Mixtape title<small>"Mixtape info"</small></h4>
						</div>
					</a>
					<div class="isotope-alt-details">
						<div>
							<h4 class="remove-bottom">Mixtape title</h4>
							<p class="meta">Mixtape releasedate</p>
						</div>
					</div>
				</li>
			</ul>	
		</div>
		
	</section>
	<!-- Contact Form -->
	<section class="small-padding" id="contact">
		<div class="wrapper">
			<h3 class="floatleft">Contact</h3>
            
			<div class="clear"></div><!--CLEAR FLOATS-->
		</div>
	</section>


    <!-- Contact Modal -->
	<section class="dark-wrapper">
		<div class="wrapper clearfix">
			<div class="two_thirds scroll-animate left">
                <button class="button white light2" data-toggle="modal" data-target="#contactModal">Contact Us</button>
            </div>
		</div>
	</section>
	
	<footer>
		<div class="wrapper centered">
			<div class="social">
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-dribbble"></i></a>
				<a href="#"><i class="fa fa-flickr"></i></a>
				<a href="#"><i class="fa fa-github"></i></a>
			</div>
			<div class="clear"></div><!--CLEAR FLOATS-->
		</div>
	</footer>
	
	<section class="small-padding dark-wrapper">
		<div class="wrapper">
			<p class="centered"></p>
			<div class="clear"></div><!--CLEAR FLOATS-->
		</div>
	</section>
	
<!--LOAD SCRIPTS-->
<script src="js/jquery-1.11.0.js"></script>
<script type="text/javascript" src="js/jquery.modal.js"></script>
<script type="text/javascript" src="js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/plugins.js"></script>
<script type="text/javascript" src="js/custom.js"></script>
<script type="text/javascript" src="js/style.js"></script>
<script type="text/javascript" src="js/video.js"></script>
<script>
    $(function() {
        var BV = new $.BigVideo({useFlashForFirefox:false});
		BV.init();
		if ((/iPhone|iPod|iPad|Android|BlackBerry/).test(navigator.userAgent)) {
		    BV.show('https://i.ytimg.com/vi/zta6Z1HN6I8/hqdefault.jpg');
		} else {
		    BV.show('https://www.youtube.com/watch?v=zta6Z1HN6I8',{
		    	altSource:'http://video-js.zencoder.com/oceans-clip.ogv'
		    });
		}
		BV.getPlayer().volume(0);
		
		$('body').on('click', '.mute.muted', function(){
			BV.getPlayer().volume(0.8);
			$(this).removeClass('muted').addClass('unmuted');
			return false;
		});
		
		$('body').on('click', '.mute.unmuted', function(){
			BV.getPlayer().volume(0);
			$(this).removeClass('unmuted').addClass('muted');
			return false;
		});
    });
</script>
    <!-- Video Modal -->
    <div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModalLabel" aria-hidden="true" style="color:#333">
                    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="videoModalLabel"><strong>Video Title</strong></h4>
                        </div>
                        <div class="modal-body">
                            Video goes here
                    </div>
                 </div>
            </div>
        </div>

    <!-- Contact Modal -->
    <div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel" aria-hidden="true" style="color:#333">
                    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="contactModalLabel"><strong>Become a ????</strong></h4>
                        </div>
                        <div class="modal-body">
                        <form  action="/formsub" method="POST">
                        <div class="form-group">
                            <label for="exampleInputEmail1"><strong>First Name</strong></label>
                            <input type="text" name="first_name" class="form-control" id="first_name" placeholder="First Name">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1"><strong>Last Name</strong></label>
                            <input type="text" name="last_name" class="form-control" id="last_name" placeholder="Last Name">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1"><strong>Email</strong></label>
                            <input type="email" name="email" class="form-control" id="email" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1"><strong>Phone Number</strong></label>
                            <input type="number" name="phone_number" class="form-control" id="phone_number" placeholder="Number">
                        </div>
                        <div class="form-group">
                        <label for="exampleInputEmail1"><strong>Carrier</strong></label>
                        <select name="phone_carrier" class="form-control" id="phone_carrier">
                            <option>Please Select</option>
                            <option>Verizon</option>
                            <option>Sprint</option>
                            <option>T-Mobile</option>
                            <option>AT&T</option>
                            <option>Other</option>
                        </select>
                        </div>
                        <div class="form-group">
                        <label for="exampleInputEmail1"><strong>Instagram Handle</strong></label>
                        <div class="input-group">
                            <span class="input-group-addon">@</span>
                            <input type="text" name="ig_handle" class="form-control" id="ig_handle" placeholder="Instagram Handle" >
                        </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1"><strong>Twitter Handle</strong></label>
                            <div class="input-group">
                                <span class="input-group-addon">@</span>
                                <input type="text" name="tw_handle" class="form-control"   id="tw_handle" placeholder="Twitter Handle">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1"><strong>Facebook Username or Email Address</strong></label>
                            <input type="text" name="fb_handle" class="form-control" id="fb_handle" placeholder="Facebook Username or Email Address">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1"><strong>Perfered Contact Method</strong></label><br/>
                            <label class="radio-inline";font-weight:bold;">
                            <input style ="width: 5%" type="radio" name="preferred" id="perferedmethod radioStyle" value="SMS">&nbsp;<strong>Text Message</strong> 
                            </label>
                        <label class="radio-inline";font-weight:bold;">
                            <input style ="width: 5%" type="radio" name="preferred" id="perferedmethod1 radioStyle" value="Email">&nbsp;<strong>Email</strong>
                        </label>

                        <input type="hidden" name="returnplease" class="form-control" id="returnplease" placeholder="" value="{{Request::path()}}">

                        </div>
                        <div id ="center"class="modal-footer">
                            <br />
                            <input type="submit" class="btn btn-default" value="Submit">
                        </div>
                    </form>
                    </div>
                 </div>
            </div>
        </div>
</body>
</html>