<?php 
echo <<<EOT
	<footer>
		<div class="wrapper centered">
			<div class="social">
				<a href="https://twitter.com/youngmoney_yawn"><i class="fa fa-twitter"></i></a>
				<a href="http://instagram.com/youngmoney_yawn"><i class="fa fa-instagram"></i></a>
				<a href="https://www.facebook.com/pillsandwateryawn"><i class="fa fa-facebook"></i></a>
				<a href="https://www.youtube.com/user/CreativeNation757"><i class="fa fa-youtube"></i></a>
			</div>
			<div class="clear"></div><!--CLEAR FLOATS-->
		</div>
	</footer>
EOT;
?>