<?php 
echo <<<EOT
 <!-- Image Modal  -->
    <div class="modal fade" id="imageModal" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel" aria-hidden="true" style="color:#333">
                    <div class="modal-dialog" id="image-modal-dialog">
                    <div class="modal-content" id="image-modal-content">
                        <div class="modal-header" id="image-modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        	</br>
                        </div>
                        <div class="modal-body" id="image-modal-body">
                            <iframe scrolling='yes' width='100%' height='352' scrollbars='no' frameborder='0'></iframe>
                    </div>
                 </div>
            </div>
        </div>
EOT;
?>