<?php 
echo <<<EOT
    <!-- Mixtape Modal  -->
    <div class="modal fade" id="mixtapeModal" tabindex="-1" role="dialog" aria-labelledby="mixtapeModalLabel" aria-hidden="true" style="color:#333">
                    <div class="modal-dialog" id="mixtape-modal-dialog">
                    <div class="modal-content" id="mixtape-modal-content">
                        <div class="modal-header" id="mixtape-modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="mixtapeModalLabel"><strong>Mixtape Title</strong></h4>
                        </div>
                        <div class="modal-body" id="mixtape-modal-body">
                            <iframe scrolling='no' width='100%' height='352' scrollbars='no' frameborder='0'></iframe>
                    </div>
                 </div>
            </div>
        </div>
EOT;
?>