<?php 
echo <<<EOT
	<!-- Video Modal -->
    <div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModalLabel" aria-hidden="true" style="color:#333">
                    <div class="modal-dialog" id="video-modal-dialog">
                    <div class="modal-content" id="video-modal-content">
                        <div class="modal-header" id="video-modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="videoModalLabel"><strong>Video Title</strong></h4>
                        </div>
                        <div class="modal-body" id="video-modal-body">
                            <iframe width="100%" height="315" frameborder="0" allowfullscreen id="video-iframe"></iframe>
                        </div>
                 </div>
            </div>
        </div>
EOT;
?>